### ISSUE TITLE
US 13 - Backend Create Recipes

### ISSUE THREAD

**Issue by nora-kauczor** [Larissartoricader/Capstone#22]
## Value proposition
**As a User**
**I want to** store my created recipes online
**In order** to keep them safe and accessible from everywhere
## Acceptance criteria
- [ ] The user can still create new recipes, but they are now being stored in and fetched from the data base
- [ ] If the method fails, an error message is displayed
## Tasks
- [ ] create feature branch `feature/backend-create`
- [ ] refactor the `RecipeForm` by implementing the method for `CREATE`

**Comment by benediktbrenk** [comment]
You need to refactor not only the form's fetching logic, but also the API: "if (request.method === "POST")..." --> acceptance criteria: the API receives the POST-request and sends to the data to the database
