### ISSUE TITLE
US 14 - US 13 - Backend Update Recipes

### ISSUE THREAD

**Issue by nora-kauczor** [Larissartoricader/Capstone#23]
## Value proposition
**As a User**
**I want to** store my created recipes online
**In order** to keep them safe and accessible from everywhere
## Acceptance criteria
- [ ] The user can still create new recipes, but they are now being stored in and fetched from the data base
- [ ] If the method fails, an error message is displayed
## Tasks
- [ ] create feature branch `feature/backend-create`
- [ ] refactor the `RecipeForm` by implementing the method for `CREATE`

**Comment by benediktbrenk** [comment]
The same as read

**Comment by MareikeFla** [comment]
Hi :) The request method for updating is called [POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST)
Also I think you have to create your POST functionallity in the api route, not in RecipeForm?
