### ISSUE TITLE
US 16 - Refine Form

### ISSUE THREAD

**Issue by nora-kauczor** [Larissartoricader/Capstone#25]
## Value proposition
**As a User** interested in natural health recipes,
**I want to** create and store new recipes,
**so that** I can keep track of my homemade solutions and use them whenever needed.
## Description
![Image](https://github.com/Larissartoricader/Capstone/assets/160526052/eee6416c-0e84-407f-83e2-bd9333669a98)
## Acceptance criteria
- [ ] A Form Page for adding recipes is displayed when clicking on a "+"-button.
- [ ] Delete asteriks from the input field's labels as they're all required
- [ ] The recipe `title`, `ingredients`, `preparation` has a with a character limit between 1 and 150.
- [ ] When filling out a field and trying to submit (even thought not having filled all fields), the cursor jumps to the next field below.
- [ ] The `symptoms` field must have a default option, "Please select a symptom" and require a selection.
- [ ] Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- [ ] There is a "cancel"-button to end the progress of adding a recipe without saving and the user is redirected to the RecipesList.
## Tasks TODO
- [ ] List the tasks that need to be performed within the dev team

**Comment by E-Swoboda** [comment]
Your plan for refining the recipe form seems well thought out and user focused. Overall, I find these refinements to be thoughtful and aligned with best practices in user interface design and user experience. They prioritize usability, clarity, and user control, which are crucial aspects of creating a positive interaction with the recipe form.
