### ISSUE TITLE
US 13 - Backend Read Recipe

### ISSUE THREAD

**Issue by Larissartoricader** [Larissartoricader/Capstone#26]
## Value proposition
As a user
I want to be able to see a list of Recipes and also the Detail Page about each Recipe individually. 
In order to now exactly to prepare and to usage the choose Recipe
## Description
- No design required
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] Use the new existing API to fetch the data to the `_app.js` files
- [ ] Check if the data, now coming from the API, reaches all the components and shows the content on the pages: Recipe List, Recipe Details Page.  Important: Keep the same `recipes` name as props to ensure that all the components not yet merged in this version work.
