### ISSUE TITLE
Refine Form #2

### ISSUE THREAD

**Issue by nora-kauczor** [Larissartoricader/Capstone#29]
## Value proposition
As a user
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] The user cannot exit the form site by clicking the back button of the browser.
- [ ] 
- [ ] Implement different headline (and text of submit button) when the user is __editing__ and when he's creating a __new__ recipe
## Tasks
- [ ] List the tasks that need to be performed within the dev team
