### ISSUE TITLE
New Collections for Ingredients and Symptoms [To be discussed ]

### ISSUE THREAD

**Issue by Larissartoricader** [Larissartoricader/Capstone#33]
## Value Proposition
As a Developer, I want to update the Ingredients and Symptoms collections in MongoDB whenever a user creates a new recipe. This ensures that our lists of ingredients and symptoms are always up-to-date and enables us to provide relevant suggestions to users more frequently.

## Description
- No design changes required.

## Acceptance Criteria
- [ ] Two new collections created in MongoDB based on initial recipes.
- [ ] Establish connection between the new collections and the existing Recipe Collection.

## Tasks
- [ ] Update the existing Recipe collection in MongoDB to incorporate data from the Ingredients and Symptoms collections.
- [ ] Modify RecipeForm and FilterForm to fetch suggestions from the new collections in MongoDB.
- [ ] Enable the two new collections to accept new entries when users create new recipes.
