### ISSUE TITLE
US 18 - Random Tip of The Day

### ISSUE THREAD

**Issue by nattenhagen** [Larissartoricader/Capstone#34]
## Value proposition
As a user
I want to see a great tip of the day on top of my homepage in my the app
In order to get an inspiring input for a new recipe to try

## Description
- Scribble / design or text
- Precise, no unnecessary information

![Image](https://github.com/Larissartoricader/Capstone/assets/160592282/f8172e8d-68ba-4ca0-855d-2f16ef1790be)

## Acceptance criteria

- [ ] -  On top of the Homepage a randomly spotlighted Tip of the Day should appear
- [ ] -  The spotlight displays a preview of a RecipeCard
- [ ] -  Beneath the highlight the list of recipes should appear

## Tasks

- [ ]  Make a new component for Tip of the Day on top of the RecipeList
- [ ]  On top of the Homepage implement a randomly suggested Tip of the day
- [ ]  Let it display the picture, Title and and symptoms
