### ISSUE TITLE
US 26 Styling Part #2

### ISSUE THREAD

**Issue by Larissartoricader** [Larissartoricader/Capstone#55]
## Value proposition
As a <user/role>
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] Read more from Get Random Tipp delete and keep the button around the whole card
- [ ]
