### ISSUE TITLE
DS/US Suggestions in Form and Filter

### ISSUE THREAD

**Issue by nora-kauczor** [Larissartoricader/Capstone#57]
## Value proposition
As a user
I want to see all available words matching my input while typing
In order to easily pick the words I have in mind.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] When the user enters a letter, all ingredients matching his input are displayed inside a drop down below
- [ ] When typing a second letter, only the ingredients that have those two letters at their beginning etc. 
- [ ] Same functionality for symptoms
## Tasks
- [ ] Return all of the "matches" when user is typing on change
