### ISSUE TITLE
US 32 - Loading Message

### ISSUE THREAD

**Issue by nora-kauczor** [Larissartoricader/Capstone#69]
## Value proposition
**As a** user,
**I want to** see some kind of a loading screen,
**In order to** be informed about the process of creating a recipe.

## Description
![Image](https://github.com/Larissartoricader/Capstone/assets/160526052/e1a67d59-6b72-4ad1-87c7-dd98059ae6db)

## Acceptance criteria
- [ ] when clicking the `save button` an informational message/ loading spinner is shown for a few seconds
- [ ] right before the user is redirected to the homepage the message disappears 

## Tasks
- [ ] create a feature branch `feature/loading-message`
- [ ] install the loading spinner library
- [ ] implement it on the RecipeForm
