### ISSUE TITLE
Last Minute Topics - US to be created

### ISSUE THREAD

**Issue by Larissartoricader** [Larissartoricader/Capstone#74]
## Value proposition
As a <user/role>
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] Login - Menu
- [ ]
