### ISSUE TITLE
Backend Secute and Personalize Data

### ISSUE THREAD

**Issue by Larissartoricader** [Larissartoricader/Capstone#77]
### Value Proposition
As a user, I want to identify which recipes were created by me or other users so that I can edit or delete only my own recipes.

### Description
- No design work is needed for this feature.

### Acceptance Criteria
- [ ] Only logged-in users can create a recipe.
- [ ] The backend can only be accessed by logged-in users.
- [ ] Only the author of a recipe can delete or edit it.
- [ ] Specify the text for alerts when unauthorized actions are attempted.

### Tasks
- [ ] Add a new property for the recipe's author.
- [ ] Secure the backend to ensure only logged-in users can access it.
- [ ] Implement edit and delete functions that are only available if the logged-in user is the author of the recipe.

**Comment by SwethaJanardhana** [comment]
LGTM , it would be nice if you could work this US on a separate feature branch :  create a feature branch feature/backendSecure and include it in `Tasks`
