### ISSUE TITLE
US 35 a11y (in progress)

### ISSUE THREAD

**Issue by nora-kauczor** [Larissartoricader/Capstone#83]
## Value proposition
As a user
I want an app that is accessible for everyone
In order everyone to easily access and operate the app
## Description
No wireframe needed.
## Acceptance criteria
- [ ] Alternative text (alt text) for images
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] List the tasks that need to be performed within the dev team

**Comment by E-Swoboda** [comment]
Your user story addresses critical aspects of accessibility. The tasks are clear and actionable, ensuring that the app will be usable by a wide range of users. It's an excellent approach to making your app more inclusive and accessible.
