### ISSUE TITLE
US 37 - Style Refinement

### ISSUE THREAD

**Issue by nora-kauczor** [Larissartoricader/Capstone#85]
## Value proposition
As a User
I want a nice consistent design
In order to have a pleasant experience
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] A newly created recipe should be the first one in the list
- [ ] Style Buttons (see mock-up)
- [ ] Style Nav Bar (see mock-up)
- [ ] Possibly refine styling of cards regarding spacings
## Tasks
- [ ]
